name: GigaChat request and publish

on:
  workflow_dispatch:  # запуск вручную

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run GigaChat script
        run: python gigachat_request.py
        env:
          GIGACHAT_API_KEY: ${{ secrets.GIGACHAT_API_KEY }}

      - name: Publish result to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          keep_files: true
          allow_empty_commit: true
